#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

use ToBigQuery\PullMagentoOrdersCommand;
use ToBigQuery\PushMagentoOrdersToBigQueryCommand;

$application = new Application;

$application->add(new PullMagentoOrdersCommand);
$application->add(new PushMagentoOrdersToBigQueryCommand);

$application->run();
