#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

use ToBigQuery\PullMagentoOrdersCommand;

$application = new Application;

$application->add(new PullMagentoOrdersCommand);

$application->run();
